---

- name: backup | stat .npmrc
  stat: >
    path="{{ npmrc_dest }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: npmrc_stat
  tags:
    - nodejs
    - npm
    - backup

- name: backup | back up existing .npmrc
  command: >
    mv "{{ npmrc_dest  }}" "{{ npmrc_dest }}-{{ bck_stamp }}"
    removes="{{ npmrc_dest }}"
  when: npmrc_stat.stat.exists
  tags:
    - nodejs
    - npm
    - backup

- name: nodejs | generate .npmrc
  template: >
    src="{{ npmrc_src }}"
    dest="{{ npmrc_dest }}"
    force=no
  tags:
    - nodejs
    - npm
    - copy
