---

- name: backup | stat .pyenv/
  stat: >
    path="{{ pyenv }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: pyenv_stat
  tags:
    - python
    - pyenv
    - backup

- name: backup | back up existing .pyenv/
  command: >
    mv "{{ pyenv }}" "{{ pyenv }}-{{ bck_stamp }}"
    removes="{{ pyenv }}"
  when: pyenv_stat.stat.exists
  tags:
    - python
    - pyenv
    - backup

- name: python | install default global packages
  pip: >
    name="{{ item }}"
    state=latest
  with_items: "{{ python_packages }}"
  tags:
    - python
    - pip
    - install
