---

- name: backup | stat .gemrc
  stat: >
    path="{{ gemrc_dest }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: gemrc_stat
  tags:
    - ruby
    - rubygems
    - backup

- name: backup | back up existing .gemrc
  command: >
    mv "{{ gemrc_dest }}" "{{ gemrc_dest }}-{{ bck_stamp }}"
    removes="{{ gemrc_dest }}"
  when: gemrc_stat.stat.exists
  tags:
    - ruby
    - rubygems
    - backup

- name: ruby | link .gemrc
  file: >
    src="{{ gemrc_src }}"
    dest="{{ gemrc_dest }}"
    state=link
    force=no
  tags:
    - ruby
    - rubygems
    - link

- name: backup | stat .rbenv/
  stat: >
    path="{{ rbenv_dest }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: rbenv_stat
  tags:
    - ruby
    - rbenv
    - backup

- name: backup | back up existing .rbenv/
  command: >
    mv "{{ rbenv_dest }}" "{{ rbenv_dest}}-{{ bck_stamp }}"
    removes="{{ rbenv_dest }}"
  when: rbenv_stat.stat.exists
  tags:
    - ruby
    - rbenv
    - backup

- name: ruby | link .rbenv/
  file: >
    src="{{ rbenv_src }}"
    dest="{{ rbenv_dest }}"
    state=link
    force=no
  tags:
    - ruby
    - rbenv
    - link

- name: backup | stat .rbenv/plugins/
  stat: >
    path="{{ rbenv_plugins_dest }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: rbenv_plugins_stat
  tags:
    - ruby
    - rbenv
    - rbenv-plugins
    - backup

- name: backup | back up existing .rbenv/plugins/
  command: >
    mv "{{ rbenv_plugins_dest }}" "{{ rbenv_plugins_dest }}-{{ bck_stamp }}"
    removes="{{ rbenv_plugins_dest }}"
  when: rbenv_plugins_stat.stat.exists
  tags:
    - ruby
    - rbenv
    - rbenv-plugins
    - backup

- name: ruby | link .rbenv/plugins/
  file: >
    src="{{ rbenv_plugins_src }}"
    dest="{{ rbenv_plugins_dest }}"
    state=link
    force=no
  tags:
    - ruby
    - rbenv
    - rbenv-plugins
    - link

- name: backup | stat .rbenv/default-gems
  stat: >
    path="{{ default_gems_dest }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: default_gems_stat
  tags:
    - ruby
    - rubygems
    - rbenv
    - rbenv-plugins
    - backup

- name: backup | back up existing .rbenv/default-gems
  command: >
    mv "{{ default_gems_dest }}" "{{ default_gems_dest }}-{{ bck_stamp }}"
    removes="{{ default_gems_dest }}"
  when: default_gems_stat.stat.exists
  tags:
    - ruby
    - rubygems
    - rbenv
    - rbenv-plugins
    - backup

- name: ruby | link .rbenv/default-gems
  file: >
    src="{{ default_gems_src }}"
    dest="{{ default_gems_dest }}"
    state=link
    force=no
  tags:
    - ruby
    - rubygems
    - rbenv
    - rbenv-plugins
    - link
