---

- name: rust | install Rust
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path"
  #                                                  │        └─ don't modify PATH on install
  #                                                  └─ non-interactive install
  tags:
    - rust
    - rustup
    - install

- name: rust | gather installed package information
  stat: >
    path="{{ rust_cargo_path }}/bin/{{ item }}"
    follow=yes
    get_checksum=no
    get_md5=no
  with_items: "{{ rust_packages }}"
  register: rust_package_stats
  tags:
    - rust

- name: rust | install global packages
  shell: >
    cargo install --force "{{ item.item }}"
  with_items: "{{ rust_package_stats.results }}"
  when: not item.stat.exists
  tags:
    - rust
    - cargo
    - install
