---

- name: backup | stat .tmux.conf
  stat: >
    path="{{ tmux_conf_dest }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: tmux_conf_stat
  tags:
    - tmux
    - backup

- name: backup | back up existing .tmux.conf
  command: >
    mv "{{ tmux_conf_dest }}" "{{ tmux_conf_dest }}-{{ bck_stamp }}"
    removes="{{ tmux_conf_dest }}"
  when: tmux_conf_stat.stat.exists
  tags:
    - tmux
    - backup

- name: tmux | link .tmux.conf
  file: >
    src="{{ tmux_conf_src }}"
    dest="{{ tmux_conf_dest }}"
    state=link
    force=no
  tags:
    - tmux
    - link

- name: backup | stat .tmux/
  stat: >
    path="{{ tmux_dest }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: tmux_stat
  tags:
    - tmux
    - backup

- name: backup | back up existing .tmux/
  command: >
    mv "{{ tmux_dest }}" "{{ tmux_dest }}-{{ bck_stamp }}"
    removes="{{ tmux_dest }}"
  when: tmux_stat.stat.exists
  tags:
    - tmux
    - backup

- name: tmux | link .tmux/
  file: >
    src="{{ tmux_src }}"
    dest="{{ tmux_dest }}"
    state=link
    force=no
  tags:
    - tmux
    - link

- name: tpm | ensure tpm is installed
  stat: >
    path="{{ tpm }}"
    get_checksum=no
    get_md5=no
  register: tpm_stat
  tags:
    - tmux
    - tpm

- name: tpm | install tmux plugins
  command: "{{ tpm }}/bin/install_plugins"
  when: tpm_stat.stat.exists
  tags:
    - tmux
    - tpm
    - tmux-plugins
