---

- name: zsh | add brewed zsh to /etc/shells
  lineinfile: >
    dest="/etc/shells"
    state=present
    line="/usr/local/bin/zsh"
    insertbefore="/bin/bash"
  sudo: yes
  tags:
    - zsh
    - shell
    - chsh

- name: zsh | set default shell to zsh
  command: >
    chsh -s /usr/local/bin/zsh "{{ ansible_env['USER'] }}"
  sudo: yes
  tags:
    - zsh
    - shell
    - chsh

- name: backup | gather zsh-related information
  stat: >
    path="{{ item.value.dest }}"
    follow=no
    get_checksum=no
    get_md5=no
  with_dict: "{{ zsh_files }}"
  register: zsh_file_stats
  tags:
    - zsh

- name: backup | back up existing zsh-related files
  command: >
    mv "{{ item.item.value.dest }}" "{{ item.item.value.dest }}-{{ bck_stamp }}"
    removes="{{ item.item.value.dest }}"
  with_items: "{{ zsh_file_stats.results }}"
  when: item.stat.exists
  tags:
    - zsh
    - backup

- name: zsh | link zsh-related files
  file: >
    src="{{ item.item.value.src }}"
    dest="{{ item.item.value.dest }}"
    state=link
    force=no
  with_items: "{{ zsh_file_stats.results }}"
  tags:
    - zsh
    - link
