---

- name: homebrew | check if Homebrew is installed
  stat: >
    path="{{ homebrew_exec }}"
    follow=no
    get_checksum=no
    get_md5=no
  register: homebrew_exec_stat
  tags:
    - homebrew

- name: homebrew | tap additional repos
  homebrew_tap: >
    tap="{{ item }}"
    state=present
  with_items: "{{ homebrew_taps }}"
  when: homebrew_exec_stat.stat.exists
  tags:
    - homebrew
    - taps

- name: homebrew | update Homebrew
  homebrew: >
    update_homebrew=yes
  when: homebrew_exec_stat.stat.exists
  tags:
    - homebrew
    - brews
    - install
    - update

- name: homebrew | install brews
  homebrew: >
    name="{{ item.name }}"
    install_options="{{ item.options | default() }}"
    state=latest
  with_items: "{{ homebrew_brews }}"
  when: homebrew_exec_stat.stat.exists
  tags:
    - homebrew
    - brews
    - install
    - update

- name: homebrew | install casks
  homebrew_cask: >
    name="{{ item }}"
    state=present
  sudo: yes
  with_items: "{{ homebrew_casks }}"
  when: homebrew_exec_stat.stat.exists
  tags:
    - homebrew
    - casks
    - install
