#!/usr/bin/env bash

set -e

OS="$(uname -s)"

_is_missing () {
  ! hash "$1" 2>/dev/null
}

_write_out () {
  local input_len=${#1}
  local len=$((input_len + 4))

  printf "\n"
  printf '%*s' "$len" '' | tr ' ' "="
  printf "\n‖ %s ‖\n" "$1"
  printf '%*s' "$len" '' | tr ' ' "="
  printf "\n\n"
}

_brew_install () {
  if _is_missing brew
  then
    printf "Missing executable \`brew\`, exiting...\n"
    exit 1
  fi

  brew install "$1"
}

_check_status () {
  if [[ $1 -ne 0 ]]
  then
    exit "$1"
  fi
}

# Ensure we have necessary dependencies
if [[ $OS == "Darwin" ]]
then
  if _is_missing "brew"
  then
    _write_out "Homebrew is not installed, installing..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    _check_status $?
  fi

  # Set $PATH to use brewed versions instead of system ones
  export PATH=/usr/local/bin:$PATH

  if _is_missing "git"
  then
    _write_out "git is not installed, installing..."
    _brew_install "git"
    _check_status $?
  fi

  printf "Dependencies installed. All done.\n"
else
  printf "This is an unsupported OS identified as %s.\n" "$OS"
fi
